### ISSUE TITLE
A relevant work

### ISSUE THREAD

**Issue by Ki-Seki** [SihengLi99/LLM-Honesty-Survey#1]
Congratulations! 🎉 Thank you for your valuable work. Here, I would like to present our survey that might be helpful to you as well:

- **Internal Consistency and Self-Feedback in Large Language Models: A Survey**  
    *arXiv*, 2024.07.
    [arXiv](https://arxiv.org/abs/2407.14507) / [GitHub](https://github.com/IAAR-Shanghai/ICSFSurvey) / [Hugging Face](https://huggingface.co/papers/2407.14507) / [X Thread](https://x.com/Ki_Seki_here/status/1836020241538908529) / [WeChat Article](https://mp.weixin.qq.com/s/fSc0Szi-zO6YVwp2oV8Uhg)

**Comment by SihengLi99** [comment]
Thank you for your patience. This is an excellent piece of work, and we will take the time to study it thoroughly!

Best regards,
Siheng
